name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Run cargo-udeps
      uses: aig787/cargo-udeps-action@v1
      with:
          version: 'latest'
          args: '--all-targets'
